# Generated by Django 5.2.1 on 2025-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index2', '0002_remove_profile_user_profile_id_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
