# Generated by Django 5.2.1 on 2025-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(max_length=35),
        ),
    ]
