# Generated by Django 5.2.1 on 2025-06-03 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_stuff_stuff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
