# Generated by Django 5.2.1 on 2025-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
